### PR TITLE
added: rule GroupByKeyRenameColumnQQ

### PR DESCRIPTION
**Pull request by mvasyliv**

### CODE REVIEW

**Comment by holdenk** [comment]
Can you share some context on the difference between this one and the other? Similarily here I think it would be good to add a negative test.

**Comment by mvasyliv** [comment]
1. rules with ....QQ use quasiquotes.
2. prior version rules use scalameta-ast.
3. Similarily here I think it would be good to add a negative test. >>>
this rule have :
in input:
    val c = List("Person 1", "Person 2", "User 1", "User 3", "test")
      .toDS()
      .withColumnRenamed("value", "newColName")
      .count()
      
      in output:
          val c = List("Person 1", "Person 2", "User 1", "User 3", "test")
      .toDS()
      .withColumnRenamed("value", "newColName")
      .count()
      
      we can edit in output. "value" rename to "key" 
      and received *** FAILED *** test

**Comment by holdenk** [comment]
Yeah lets add some negative tests to both the QQ rules.

**Comment by mvasyliv** [comment]
TODO: test inSource3.
      1. Rule not work.
      2. Need add checking all source code

**Pull request closed without merging**
